#!/bin/bash
# The following attributes have been applied to various tests, to control
# which tests are executed:
#   * 'qa'
#   * 'slow'
# The run the "short" unit test suite, do the following:
# $ ./run_tests --with-doctest -a '!qa,!slow' --with-coverage --cover-package=openquake

# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or moved.
find . -name "*.pyc" -delete

# Use the current dir as a working directory for test discovery.
# This should pick up everything in tests/ and qa_tests/
(export DJANGO_SETTINGS_MODULE="openquake.engine.settings";
 # PYTHONPATH="$PYTHONPATH:openquake/nrml";
 python /usr/bin/nosetests "$@" -w . 2>&1 | tee last_test_run.log)
