# Generated by Django 4.2.10 on 2024-11-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('server', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, defaults={'interface_level': '1'})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('interface_level', models.CharField(choices=[('0', 'View Only'),
                                                              ('1', 'Simplified'),
                                                              ('2', 'Advanced')],
                                                     default='1',
                                                     max_length=10)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_profiles),
    ]
