---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /mnt/nfs:/opt:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - master
  - name: worker1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /mnt/nfs:/opt:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - worker
  - name: worker2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /mnt/nfs:/opt:ro
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - worker
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - converge
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      ansible_verbosity: 1
  lint:
    ansible-lint
