---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: master
  become: yes
  become_user: openquake
  gather_facts: false

  tasks:
  - name: Run a Demo calc for EventBasedRisk using https
    command: /usr/bin/oq engine --run "https://github.com/gem/oq-engine/blob/master/openquake/server/tests/data/classical.zip?raw=true"
    args:
      chdir: /home.dev/openquake
  
  - name: Display outputs of last calculcation 
    command: /usr/bin/oq engine --list-outputs -1
    args:
      chdir: /home.dev/openquake
    register: calc
  - debug: msg="{{ calc.stdout }}"
