apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: openquake/engine:nightly
        ports:
        - name: webui
          containerPort: 8800
