---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      ansible_verbosity: 1
  lint:
    ansible-lint
verifier:
  name: ansible
#lint: |
#  set -e
#  yamllint .
#  ansible-lint
