#!/bin/bash

tstamp=`date +"%Y-%m-%d--%H-%M-%S"`
tdir=$HOME/Documents/oq/logs/$tstamp
mkdir -p $tdir
for m in gemsun01 gemsun02 gemsun03 gemsun04 gemmicro01 gemmicro02 bigstar04
do
    scp -p root@$m.ethz.ch:/tmp/celeryd.log $tdir/$m.log
done
echo $tdir | xclip
echo $tdir 
