// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA-R39)

package junk.webservices.client;


public interface GMT_WebService extends javax.xml.rpc.Service {
    public junk.webservices.client.GMT_WebServiceAPI getGMT_WebServiceAPIPort();
}
