#!/bin/sh -e
PG_CONF="/etc/postgresql/9.1/main/postgresql.conf"

echo "CONFIG $*" >> /tmp/oq-engine.log

# Source debconf library.
. /usr/share/debconf/confmodule

#
#  NOTE
#        look 'debian/postinst' file if you want to change something here
#
# exists postgres config file ?
if [ -f "$PG_CONF" ]; then
    # is standard_conforming_strings set to the wrong value for us ?
    if grep -q '^[ 	]*standard_conforming_strings[ 	]*=[ 	]*on' "$PG_CONF" ; then
        db_input critical python-oq-engine/override-psql-std-conf-str || true
        db_go
    fi
fi
