#!/bin/sh
set -e
#set -x
#echo "ARGS POSTINST: $@"
PKGNAME=python-oq-hazardlib

ownpkg="$(dpkg -S openquake/baselib/__init__.py 2>/dev/null | grep -v '^diversion by ' | head -n 1 | sed 's/:.*//g' || true)"

if [ "$ownpkg" = "$PKGNAME" ]; then
    for i in $(dpkg-divert --list "$PKGNAME" | sed 's/^.* of //g;s/ to .*$//g') ; do
        dpkg-divert --package "$PKGNAME" --remove "$i"
        if [ -e "${i}.oq-haz" ]; then
            rm "${i}.oq-haz"
        fi
    done
fi

if which pycompile >/dev/null 2>&1; then
    pycompile -p "$PKGNAME"
fi
