openquake/engine/openquake.cfg             /etc/openquake
debian/desktop/oq-engine-webui.desktop     /usr/share/applications
debian/desktop/openquake.png               /usr/share/pixmaps
debian/supervisord/openquake-dbserver.conf /etc/supervisor/conf.d
debian/supervisord/openquake-webui.conf    /etc/supervisor/conf.d
demos                                      /usr/share/openquake/engine
utils                                      /usr/share/openquake/engine
