[general]
description = Seismic hazard analysis for Arctic ocean (PAR) 2026 calculations
calculation_mode = classical
random_seed = 23

[geometry]

site_model_file = sites_par_res4_islands_res6.csv
#site_model_file = sites_src2_only.csv

[logic_tree]

number_of_logic_tree_samples = 0

[erf]

rupture_mesh_spacing = 5
complex_fault_mesh_spacing = 10
width_of_mfd_bin = 0.1
area_source_discretization = 5.0

[site_params]

reference_vs30_type = measured
reference_vs30_value = 800.0
reference_depth_to_1pt0km_per_sec = -999 
reference_depth_to_2pt5km_per_sec = -999

[calculation]

source_model_logic_tree_file = ssmLT_test2.xml
gsim_logic_tree_file = gmmLT_simp.xml
investigation_time = 1.0
intensity_measure_types_and_levels = {"PGA": [0.001, 0.005, 0.0065, 0.0085, 0.011, 0.015, 0.019]}

truncation_level = 5
maximum_distance = {'default': 300.}
horiz_comp_to_geom_mean = true
# ps_grid_spacing = 60
