# The Hazard Library
# Copyright (C) 2012-2026 GEM Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import math
import os
import unittest
import numpy as np

from openquake.hazardlib import valid
from openquake.hazardlib.contexts import simple_cmaker
from openquake.hazardlib.gsim.mgmpe.grid_adjusted_gmpe import (
    GridAdjustedGMPE,
    grid_lookup,
    load_residual_grids,
    raytrace_path_adj,
)

aae = np.testing.assert_array_almost_equal

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
# The test HDF5 stores 10 IMTs (PGA + SA at 0.01, 0.05, 0.1, 0.2, 0.3,
# 0.5, 0.75, 1.0, 2.0). Each stored value at each IMT is generated by a
# formula linear in log10(T), so log-period interp reproduces the same
# formula exactly at any bracketed IMT (SA(0.02), SA(1.5) in the tests).
GRID_HDF5 = os.path.join(DATA_DIR, "test_grid_adjustments.hdf5")

BASE, GRID = 0, 1
BASE_GSIM = "AkkarEtAlRjb2014"
STORED_IMTS = ["PGA", "SA(0.01)", "SA(0.05)", "SA(0.1)", "SA(0.2)",
               "SA(0.3)", "SA(0.5)", "SA(0.75)", "SA(1.0)", "SA(2.0)"]
INTERP_IMTS = ["SA(0.02)", "SA(1.5)"]
LATS = np.array([0.0, 10.0, 20.0, 40.0])
LONS = np.array([0.0, 10.0, 20.0, 40.0])
DP = 4
PGA_ANCHOR = 0.01


def _period(imt_str):
    """Period used by the value formulas; PGA is anchored at 0.01 s."""
    if imt_str == "PGA":
        return PGA_ANCHOR
    return float(imt_str[3:-1])


# Value formulas — must match those in the HDF5 rebuild script.
def dL2L_val(k, T):
    return 0.05 * (k + 1) - 0.02 * (k + 1) * math.log10(T)


def dS2S_val(k, T):
    return -0.10 - 0.05 * k + 0.02 * (k + 1) * math.log10(T)


def att_per_km_val(k, T):
    return 0.005 * (k + 1) - 0.001 * (k + 1) * math.log10(T)


def dL2L_sig_val(T):
    return 0.04 - 0.005 * math.log10(T)


def dS2S_sig_val(k, T):
    return 0.04 + 0.01 * k - 0.005 * (k + 1) * math.log10(T)


def att_per_km_sig_val(T):
    return 0.00112 + 0.0002 * math.log10(T)


def dL2L_mean_per_cell(imt_str):
    T = _period(imt_str)
    return np.array([dL2L_val(k, T) for k in range(4)])


def dS2S_mean_per_cell(imt_str):
    T = _period(imt_str)
    return np.array([dS2S_val(k, T) for k in range(4)])


def dS2S_sig_per_cell(imt_str):
    T = _period(imt_str)
    return np.array([dS2S_sig_val(k, T) for k in range(4)])


# Raytrace expected values: the four test sites sit in the four
# corresponding cells (site 0 in cell 0, etc.), the hypocentre is at the
# origin, and the intersecting-cell contribution scales with the cell's
# per-km adjustment. For simplicity the tests compute the ray-trace
# adjustment via ``raytrace_path_adj`` at each stored IMT to derive the
# per-IMT expected values, then interp between the two bracketing IMTs
# for INTERP_IMTS.
def _raytrace_at_imt(imt_str, gd):
    return raytrace_path_adj(
        gd["raytrace_grids"]["att_per_km"][imt_str],
        np.zeros(len(LONS)), np.zeros(len(LATS)), LONS, LATS)


def _log_interp(target_T, T_lo, T_hi, v_lo, v_hi):
    r = ((math.log(target_T) - math.log(T_lo)) /
         (math.log(T_hi) - math.log(T_lo)))
    return v_lo + r * (v_hi - v_lo)


def _expected_path_adj(imt_str, gd):
    """
    For stored IMTs, run raytrace directly. For interpolated IMTs, run
    raytrace at the two bracketing stored IMTs then log-period interp
    (mirrors what the GSIM's per-cell interp of ``att_per_km``
    reproduces, because att_per_km_val is linear in log10 T).
    """
    if imt_str in STORED_IMTS:
        return _raytrace_at_imt(imt_str, gd)
    if imt_str == "SA(0.02)":
        lo, hi = "SA(0.01)", "SA(0.05)"
    elif imt_str == "SA(1.5)":
        lo, hi = "SA(1.0)", "SA(2.0)"
    else:
        raise ValueError(imt_str)
    v_lo = _raytrace_at_imt(lo, gd)
    v_hi = _raytrace_at_imt(hi, gd)
    return _log_interp(_period(imt_str), _period(lo), _period(hi), v_lo, v_hi)


class GridAdjustedGMPETest(unittest.TestCase):

    def _get_mean_stds(self, imts):
        base = valid.gsim(BASE_GSIM)
        adj = GridAdjustedGMPE(gmpe_name=BASE_GSIM, grid_hdf5_file=GRID_HDF5)
        cmaker = simple_cmaker([base, adj], imts)
        ctx = cmaker.new_ctx(len(LATS))
        ctx.mag = 6.0
        ctx.rake = 0.0
        ctx.hypo_depth = 10.0
        ctx.vs30 = 760.0
        ctx.rrup = np.array([10.0, 20.0, 30.0, 50.0])
        ctx.rjb = np.array([10.0, 20.0, 30.0, 50.0])
        ctx.lat = LATS
        ctx.lon = LONS
        ctx.hypo_lat = 0.0
        ctx.hypo_lon = 0.0
        return cmaker.get_mean_stds([ctx])

    def test_grid_lookup(self):
        # Direct grid_lookup returns the stored per-cell dL2L values
        gd = load_residual_grids(GRID_HDF5)
        mu = grid_lookup(
            gd["grids"]["PGA"]["dL2L"]["mean"],
            LATS, LONS, gd["h3_res"])
        aae(mu, dL2L_mean_per_cell("PGA"), decimal=DP)
        # Out-of-bounds coords receive zero correction
        mu = grid_lookup(
            gd["grids"]["PGA"]["dL2L"]["mean"],
            np.array([-80.0]), np.array([170.0]), gd["h3_res"])
        aae(mu, 0.0)

    def test_raytrace_path_adj(self):
        # Directly exercise raytrace_path_adj for each stored IMT
        gd = load_residual_grids(GRID_HDF5)
        for imt_str in STORED_IMTS:
            adjs = _raytrace_at_imt(imt_str, gd)
            # sanity: shape matches sites
            self.assertEqual(adjs.shape, (len(LATS),))

    def test_mean_and_sigma_at_stored_imts(self):
        # For every stored IMT, the corrected mean/sigma match the
        # per-cell values in the HDF5.
        gd = load_residual_grids(GRID_HDF5)
        mea, sig, tau, phi = self._get_mean_stds(STORED_IMTS)
        for m, imt_str in enumerate(STORED_IMTS):
            T = _period(imt_str)
            expected_mean_diff = (
                dL2L_mean_per_cell(imt_str)[0]  # hypo in cell 0
                + dS2S_mean_per_cell(imt_str)
                + _raytrace_at_imt(imt_str, gd))
            aae(mea[GRID, m] - mea[BASE, m], expected_mean_diff, decimal=DP)
            # dL2L uses "replace" with a scalar per IMT
            aae(tau[GRID, m], np.full(len(LATS), dL2L_sig_val(T)),
                decimal=DP)
            # phi: subtract per-cell dS2S sigma and scalar att_per_km sigma
            aae(phi[GRID, m],
                np.sqrt(phi[BASE, m] ** 2
                        - dS2S_sig_per_cell(imt_str) ** 2
                        - att_per_km_sig_val(T) ** 2),
                decimal=DP)
            aae(sig[GRID, m],
                np.sqrt(tau[GRID, m] ** 2 + phi[GRID, m] ** 2),
                decimal=DP)

    def test_interpolated_mean_and_sigma(self):
        # Values at SA(0.02) and SA(1.5) are synthesized by log-period
        # interp; because the underlying formulas are linear in log10(T),
        # the interp result matches the formula evaluated at the target
        # period exactly.
        gd = load_residual_grids(GRID_HDF5)
        mea, sig, tau, phi = self._get_mean_stds(INTERP_IMTS)
        for m, imt_str in enumerate(INTERP_IMTS):
            T = _period(imt_str)
            expected_mean_diff = (
                dL2L_mean_per_cell(imt_str)[0]
                + dS2S_mean_per_cell(imt_str)
                + _expected_path_adj(imt_str, gd))
            aae(mea[GRID, m] - mea[BASE, m], expected_mean_diff, decimal=DP)
            aae(tau[GRID, m], np.full(len(LATS), dL2L_sig_val(T)),
                decimal=DP)
            aae(phi[GRID, m],
                np.sqrt(phi[BASE, m] ** 2
                        - dS2S_sig_per_cell(imt_str) ** 2
                        - att_per_km_sig_val(T) ** 2),
                decimal=DP)

    def test_extrapolation_raises(self):
        # Target IMT outside the stored SA range raises ValueError.
        with self.assertRaises(ValueError):
            self._get_mean_stds(["SA(3.0)"])
        with self.assertRaises(ValueError):
            self._get_mean_stds(["SA(0.005)"])

    def test_error_non_random_effects_base_gsim(self):
        # Cannot apply tau/phi adjustments through a non-random-effects GMM
        with self.assertRaises(ValueError):
            GridAdjustedGMPE(
                gmpe_name="Campbell2003", grid_hdf5_file=GRID_HDF5)
