[general]
description = Download ShakeMap and prepare GMFs
calculation_mode = scenario_risk
random_seed = 152
number_of_ground_motion_fields = 3
shakemap_uri = {"kind": "file_npy", "fname": "shakefile/usp000fjta.npy"}
asset_hazard_distance = 20
truncation_level = 3
cross_correlation = yes
spatial_correlation = yes
maximum_distance = 200
secondary_perils = AllstadtEtAl2022Landslides, AllstadtEtAl2022Liquefaction
intensity_measure_types = PGA, PGV, SA(0.3), SA(1.0)
rupture_dict = {"mag": 7.0, "lon": -76.603, "lat": -13.386, "dep": 39, "rake": 0, "dip": 90, "strike": 0}
; aggregate_by = ID_0; ID_2
