#!/bin/env python
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2023, GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.
"""
Build the site model for the world and store it into an HDF5 file.
"""
import os
import numpy
from openquake.baselib import performance, hdf5, sap
from openquake.hazardlib.gsim_lt import GsimLogicTree
from openquake.commonlib import readinput


def get_gsim_lt(cwd):
    fname = os.path.join(cwd, 'gmmLTrisk.xml')
    if os.path.exists(fname):
        gsim_lt = GsimLogicTree(fname)
    else:
        gsim_lt = GsimLogicTree(os.path.join(cwd, 'gmmLT.xml'))
    return gsim_lt

                        
def main(mosaic_dir):
    """
    Build global site_model.hdf5
    """
    dic = {}
    fields = {}
    tot = 0
    trt_list = []
    for cwd, dirs, files in os.walk(mosaic_dir):
        for f in files:
            if f == 'job_vs30.ini':
                model = cwd.split('/')[-2]  # EUR, SAM, etc
                oq = readinput.get_oqparam(os.path.join(cwd, f))
                sm = readinput.get_site_model(oq)
                for row in sm:
                    dic[row['lon'], row['lat']] = row
                fields.update(sm.dtype.descr)
                tot += len(sm)
                gsim_lt = get_gsim_lt(cwd)
                for trt in gsim_lt.values:
                    trt_list.append((model, trt))
    for model, trt in trt_list:
        print('%s,%s' % (model, trt))
    fields['lon'] = numpy.float32
    fields['lat'] = numpy.float32
    smodel = numpy.zeros(len(dic), list(fields.items()))
    for i, row in enumerate(dic.values()):
        for n in row.dtype.names:
            smodel[i][n] = row[n]
    with hdf5.File('site_model.hdf5', 'w') as f:
        f['site_model'] = smodel
    print('Generated site_model.hdf5 with {:_d} sites'.format(len(smodel)))

main.mosaic_dir = 'Directory containing the hazard mosaic'


if __name__ == '__main__':
    with performance.Monitor(measuremem=True) as mon:
        sap.run(main)
    print(mon)

