#!/bin/env python
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2023, GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.

import os
import logging
from openquake.baselib import performance, sap, hdf5
from openquake.hazardlib import valid
from openquake.commonlib import readinput, datastore
from openquake.calculators import base
from openquake.engine import engine

INPUTS = dict(
    calculation_mode='event_based',
    number_of_logic_tree_samples='2000',
    ses_per_logic_tree_path='50',
    investigation_time='1',
    ground_motion_fields='false',
    minimum_magnitude='5',
    minimum_intensity='.1')
MODELS = sorted('''
ALS AUS CEA EUR HAW KOR NEA PHL ARB IDN MEX NWA PNG SAM TWN
CAN CHN IND MIE NZL SEA USA ZAF CCA JPN NAF PAC SSA WAF
'''.split())  # GLD is missing
MODELS = 'EUR MIE'.split()


def imts(dic):
    imtls = valid.dictionary(dic['intensity_measure_types_and_levels'])
    return ' '.join(imt for imt in imtls)


def check_imts(dicts, models):
    imts0 = imts(dicts[0])
    for model, imts1 in zip(models[1:], map(imts, dicts[1:])):
        if imts1 != imts0:
            raise ValueError(f'{imts1} != {imts0} for {model}')


def read_job_inis(mosaic_dir, models):
    out = []
    for model in models:
        fname = os.path.join(mosaic_dir, model, 'in', 'job_vs30.ini')
        dic = readinput.get_params(fname)
        dic.update(INPUTS)
        if 'truncation_level' not in dic:  # for CAN
            dic['truncation_level'] = '5'
            dic['intensity_measure_types_and_levels'] = '''\
            {"PGA": logscale(0.005, 3.00, 25),
            "SA(0.1)": logscale(0.005, 8.00, 25),
            "SA(0.2)": logscale(0.005, 9.00, 25),
            "SA(0.3)": logscale(0.005, 8.00, 25),
            "SA(0.6)": logscale(0.005, 5.50, 25),
            "SA(1.0)": logscale(0.005, 3.60, 25),
            "SA(2.0)": logscale(0.005, 2.10, 25)}'''
        if model in ("KOR", "JPN"):
            dic['investigation_time'] = '50'
            dic['ses_per_logic_tree_path'] = '1'
        dic['mosaic_model'] = model
        out.append(dic)
    check_imts(out, models)
    return out


def main(mosaic_dir, out):
    """
    Storing global SES
    """
    job_inis = read_job_inis(mosaic_dir, MODELS)
    with performance.Monitor(measuremem=True) as mon:
        jobs = engine.run_jobs(
            engine.create_jobs(job_inis, log_level=logging.WARN),
            concurrent_jobs=4)
        dstores = [datastore.read(job.calc_id) for job in jobs]
        oq = dstores[0]['oqparam']
        oq.inputs['gmfs'] = [ds.filename for ds in dstores]
        logging.warning(f'Saving {out}')
        with hdf5.File(out, 'w') as h5:
            base.import_gmfs_hdf5(h5, oq)
            h5['models'] = MODELS
    print(mon)

main.mosaic_dir = 'Directory containing the hazard mosaic'
main.out = 'Output file'

if __name__ == '__main__':
    sap.run(main)
