#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2025, GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.

from openquake.baselib import sap
from openquake.hazardlib import nrml

def main(trt, source_model_files):
    """
    Reduce the source models to the specified tectonic region type
    """
    for fname in source_model_files:
        root = nrml.read(fname)
        with open(fname + '~', 'wb') as out:
            root.sourceModel.nodes = [
                n for n in root.sourceModel if n['tectonicRegion']==trt]
            nrml.write(root.nodes, out)
main.trt = 'tectonic region type'
main.source_model_files = dict(help='paths to source model files', nargs='+')


if __name__ == '__main__':
    sap.run(main)
