#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2025, GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.

import pandas
from openquake.baselib import sap


def main(taxonomy_mapping: str, consequences: str):
    """
    Use the taxonomy mapping to upgrade risk_id-based consequence functions
    to taxonomy-based consequence functions
    """
    tmap = pandas.read_csv(taxonomy_mapping).set_index('conversion')
    for conseq in consequences:
        cons = pandas.read_csv(conseq).set_index('taxonomy')
        df = cons.join(tmap, how='inner')[cons.columns]
        for taxo, grp in df.groupby('taxonomy'):
            # take the first row
            grp[0:1].to_csv(conseq + '.new')

main.taxonomy_mapping = 'filename'
main.consequences = dict(help='files', nargs='+')


if __name__ == '__main__':
    sap.run(main)
