#!/usr/bin/env python
from openquake.baselib import sap
from openquake.hazardlib.contexts import ContextMaker
from openquake.hazardlib.calc.gmf import GmfComputer
from openquake.commonlib.datastore import read
from openquake.calculators.extract import read_ebrupture


def max_gmv0(calc_id: int, rup_id: int):
    dstore = read(-1)
    oq = dstore['oqparam']
    gsim_lt = dstore['full_lt'].gsim_lt
    sitecol = dstore['sitecol']
    ebr = read_ebrupture(dstore, 359)
    trt = ebr.tectonic_region_type
    rlzs_by_gsim = gsim_lt.get_rlzs_by_gsim_trt()[trt]
    param = dict(imtls=oq.imtls, min_iml=oq.min_iml,
                 truncation_level=oq.truncation_level)
    cmaker = ContextMaker(trt, rlzs_by_gsim, param)
    gc = GmfComputer(ebr, sitecol, cmaker)
    dic, dt = gc.compute_all()
    return max(dic['gmv_0'])


if __name__ == '__main__':
    print(sap.run(max_gmv0))
