#!/usr/bin/env python
#  -*- coding: utf-8 -*-
#  vim: tabstop=4 shiftwidth=4 softtabstop=4

#  Copyright (c) 2017, GEM Foundation

#  OpenQuake is free software: you can redistribute it and/or modify it
#  under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  OpenQuake is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.
import sys
import time
from openquake.baselib import node
from openquake.hazardlib import nrml, sourceconverter


def main(input_files):
    """
    Collect multiPointSources
    """
    for input_file in input_files:
        with open(input_file + '.bak', 'w') as f:
            f.write(open(input_file).read())
        inp = nrml.read(input_file) 
        sm = inp.sourceModel
        print('Converting %s' % input_file)
        sourceconverter.update_source_model(sm)
        if 'name' in sm.attrib:
            attr = {"name": sm['name']}
        else:
            attr = {}
        source_model = node.Node("sourceModel", attr, nodes=sm.nodes)
        with open(input_file, 'wb') as f:
            nrml.write([source_model], f, '%s')
        

if __name__ == '__main__':
    t0 = time.time()
    main(sys.argv[1:])
    dt = time.time() - t0
    print('Time spent: %s seconds' % dt)
