#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2017-2018 GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake. If not, see <http://www.gnu.org/licenses/>.

import json
import requests
from openquake.baselib import sap


@sap.Script
def postzip(zipfile, port=8800):
    """Post a zipfile to the WebUI"""
    dic = dict(archive=open(zipfile, 'rb'))
    # NB: there is no WebUI port in openquake.cfg for the moment
    resp = requests.post("http://localhost:%d/v1/calc/run" % port, {},
                         files=dic)
    print(json.loads(resp.text))


postzip.arg('zipfile', 'archive with the files of the computation')
postzip.arg('port', 'port to use', type=int)

if __name__ == '__main__':
    postzip.callfunc()
