#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2018 GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake. If not, see <http://www.gnu.org/licenses/>.
import logging
from openquake.baselib import sap
from openquake.commonlib import readinput, logictree
from openquake.hazardlib import nrml


class ObsoleteFormat(Exception):
    pass


def renumber(paths, number):
    srcs = []
    roots = []
    for path in paths:
        logging.info('Reading %s', path)
        root = nrml.read(path)
        if root['xmlns'] == 'http://openquake.org/xmlns/nrml/0.4':
            raise ObsoleteFormat('Please use oq upgrade_nrml .')
        srcs.extend(src['id'] for sgroup in root[0] for src in sgroup)
        roots.append(root)
    if len(srcs) == len(set(srcs)):
        # there are no duplicated source IDs
        return
    for path, root in zip(paths, roots):
        logging.info('Renumbering %s', path)
        for sgroup in root[0]:
            for src in sgroup:
                src['id'] = str(number)
                number += 1
        with open(path, 'wb') as f:
            nrml.write(root, f)


@sap.Script
def renumber_sources(smlt_file):
    """
    Renumber the sources belonging to the same source model, even if split
    in multiple files, to avoid duplicated source IDs. NB: it changes the
    XML files in place, without making a backup, so be careful.
    """
    logging.basicConfig(level=logging.INFO)
    for info in logictree.collect_info(smlt_file):
        renumber(info.smpaths, number=1)


renumber_sources.arg('smlt_file', 'source model logic tree file')

if __name__ == '__main__':
    renumber_sources.callfunc()
