#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4

# Copyright (C) 2020, GEM Foundation

# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.

import os
import json
from openquake.baselib import hdf5, sap
from openquake.hazardlib import nrml


@sap.Script
def srcs_to_rups(sm_file):
    """
    Experimental converter source_model.xml -> ruptures.hdf5
    """
    sm = nrml.to_python(sm_file, nrml.default)
    out = []
    serial = 1
    for grp in sm.src_groups:
        for src in grp:
            for rup in src.iter_ruptures():
                dic = rup.todict()
                dic['serial'] = serial
                out.append(json.dumps(dic))
                serial += 1
    name, ext = os.path.splitext(sm_file)
    with hdf5.File(name + '_rups.hdf5', 'w') as f:
        dset = f.create_dataset('ruptures', (len(out),), hdf5.vstr,
                                compression='gzip')
        dset[:] = out

srcs_to_rups.arg('sm_file', 'source model file')


if __name__ == '__main__':
    srcs_to_rups.callfunc()
