#!/usr/bin/env python
from openquake.baselib import hdf5, sap
from openquake.hazardlib import nrml, sourceconverter


@sap.Script
def xml2hdf5(fname):
    sc = sourceconverter.SourceConverter(
        area_source_discretization=10, width_of_mfd_bin=.1)
    sm = nrml.to_python(fname, sc)
    with hdf5.File(fname.replace('.xml', '.hdf5'), 'w') as f:
        f['/'] = sm


xml2hdf5.arg('fname', 'source model file in XML format')

if __name__ == '__main__':
    xml2hdf5.callfunc()
