#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright (C) 2020, GEM Foundation
#
# OpenQuake is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenQuake is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.
import os
import toml
from openquake.baselib import sap


def main(dirname):
    """
    Convert all .yml files in the given directory into .toml files,
    recursively.
    """
    import yaml
    for cwd, dir_, fnames in os.walk(dirname):
        for fname in fnames:
            if fname.endswith('.yml'):
                path = os.path.join(cwd, fname)
                with open(path) as source:
                    dic = yaml.safe_load(source.read())
                with open(path[:-3] + 'toml', 'w') as target:
                    toml.dump(dic, target)
                print('Saved %s' % target.name)


main.dirname = 'directory'


if __name__ == '__main__':
    sap.run(main)
