"""
Core computation methods for the risk 'engine'
These include Classical PSHA-based risk analysis,
and deterministic analysis based on either a set of GMF files,
or a single GMF file."""

from openquake import kvs

# risk tokens
CONDITIONAL_LOSS_KEY_TOKEN = 'LOSS_AT_'
EXPOSURE_KEY_TOKEN = 'ASSET'
GMF_KEY_TOKEN = 'GMF'
LOSS_RATIO_CURVE_KEY_TOKEN = 'LOSS_RATIO_CURVE'
LOSS_CURVE_KEY_TOKEN = 'LOSS_CURVE'
LOSS_CURVES_KEY_TOKEN = 'LOSS_CURVES'

def loss_token(poe):
    """ Return a loss token made up of the CONDITIONAL_LOSS_KEY_TOKEN and 
    the poe cast to a string """
    return "%s%s" % (CONDITIONAL_LOSS_KEY_TOKEN, str(poe))

def vuln_key(job_id):
    """Generate the key used to store vulnerability curves."""
    return kvs.generate_product_key(job_id, "VULN_CURVES")

def asset_key(job_id, row, col):
    """ Return an asset key generated by kvs._generate_key """
    return kvs.generate_key([job_id, row, col, EXPOSURE_KEY_TOKEN])

def loss_ratio_key(job_id, row, col, asset_id):
    """ Return a loss ratio key generated by kvs.generate_key """
    return kvs.generate_key([job_id, row, col, LOSS_RATIO_CURVE_KEY_TOKEN,
        asset_id])

def loss_curve_key(job_id, row, col, asset_id):
    """ Return a loss curve key generated by kvs.generate_key """
    return kvs.generate_key([job_id, row, col, LOSS_CURVE_KEY_TOKEN, asset_id])

def loss_key(job_id, row, col, asset_id, poe):
    """ Return a loss key generated by kvs.generate_key """
    return kvs.generate_key([job_id, row, col, loss_token(poe), asset_id]) 

def loss_curves_key(job_id):
    """Return the key used to store the computed loss curves."""
    return kvs.generate_key([job_id, LOSS_CURVES_KEY_TOKEN])
