name: playbook_ansible
'on':
  schedule:
    - cron: "0 6 * * *"

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        distro:
          - centos7
          - ubuntu1804
          - ubuntu2004
    env:
      working-directory: ./ansible/playbook

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install test dependencies.
        run: pip3 install molecule[docker,ansible,lint]

      - name: Run Molecule tests.
        run: molecule test
        working-directory: ${{env.working-directory}}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
