# Generated by Django 4.2.10 on 2024-11-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'level': 0})


def delete_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('user_profile', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),

                ('level', models.IntegerField(
                    choices=[(0, 'View Only'),
                             (1, 'Simplified'),
                             (2, 'Advanced')],
                    default=0,
                    help_text='Choose the level for the user')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_profiles, delete_user_profiles),
    ]
