# Generated by Django 4.2.21 on 2026-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_create_can_view_exposure_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(0, 'Read only'), (1, 'Restricted'), (2, 'Advanced')], default=0, help_text='Choose the level for the user'),
        ),
    ]
